### ISSUE TITLE
Footer is always shown

### ISSUE THREAD

**Issue by aerociety** [aerociety/wi3_web_project#10]
Footer wird immer angezeigt auch wenn er nicht angezeigt werden sollte
![image](https://user-images.githubusercontent.com/3778726/119066717-b414b180-b9e0-11eb-801e-667f47556371.png)
@ArraKis01 pls fix

**Comment by ArraKis01** [comment]
hätte sogar gesagt dass wir gar keinen footer bei register/lgoin anzeigen wollen?
