### ISSUE TITLE
Creation of successful Register site

### ISSUE THREAD

**Issue by aerociety** [aerociety/wi3_web_project#13]
Need of a new site for a successful registration

**Comment by ArraKis01** [comment]
Should we really redirect to a new site or can we just display a different body?

**Comment by aerociety** [comment]
@ArraKis01 just a message is enough. But i want some kind of confirmation to inform a user about a successful registration.

**Comment by ArraKis01** [comment]
let's use this then https://getbootstrap.com/docs/5.0/components/toasts/

**Comment by aerociety** [comment]
Done.
